/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.Archivo;
import Backend.PalabrasReservadas;
import Backend.Token;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author felip
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private String pathArchivo;
    private PalabrasReservadas reservadas;

    public InterfazPrincipal(PalabrasReservadas reservadas) {
        initComponents();
        this.reservadas = reservadas;
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
        String noFilas = "<html>";
        for (int i = 1; i < 500; i++) {
            noFilas = noFilas + i + "<br>";
        }
        noFilas = noFilas + "</html>";
        filas.setText(noFilas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        filas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaArchivoLeido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Léxico");
        setMinimumSize(new java.awt.Dimension(900, 849));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        btnAbrir.setBackground(new java.awt.Color(204, 255, 255));
        btnAbrir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(0, 0, 0));
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoAbrir.png"))); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.setFocusPainted(false);
        btnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAbrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAbrirMouseExited(evt);
            }
        });
        btnAbrir.addActionListener(this::btnAbrirActionPerformed);

        btnEditar.setBackground(new java.awt.Color(204, 255, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoEditar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusPainted(false);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnAnalizar.setBackground(new java.awt.Color(204, 255, 255));
        btnAnalizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoAnalizar.png"))); // NOI18N
        btnAnalizar.setText("Analizar");
        btnAnalizar.setFocusPainted(false);
        btnAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnalizarMouseExited(evt);
            }
        });
        btnAnalizar.addActionListener(this::btnAnalizarActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(204, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoGuardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFocusPainted(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnEditar)
                    .addComponent(btnAnalizar)
                    .addComponent(btnGuardar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        filas.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        filas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filas.setText("0");
        filas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(filas, java.awt.BorderLayout.LINE_START);

        txtAreaArchivoLeido.setColumns(20);
        txtAreaArchivoLeido.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtAreaArchivoLeido.setRows(5);
        jScrollPane1.setViewportView(txtAreaArchivoLeido);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseEntered
        btnAbrir.setBackground(Color.yellow);
    }//GEN-LAST:event_btnAbrirMouseEntered

    private void btnAbrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirMouseExited
        btnAbrir.setBackground(new Color(204, 255, 255));
    }//GEN-LAST:event_btnAbrirMouseExited

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        txtAreaArchivoLeido.setEnabled(true);
        JFileChooser selector = new JFileChooser();
        selector.setAcceptAllFileFilterUsed(false);
        selector.setFileFilter(new FileNameExtensionFilter("Seleccione el archivo pz", "pz"));
        selector.showOpenDialog(this);
        pathArchivo = String.valueOf(selector.getSelectedFile());

        String archivoLeido;

        Archivo leerArchivo = new Archivo();
        archivoLeido = leerArchivo.LeerArchivo(pathArchivo);

        txtAreaArchivoLeido.setEnabled(false);
        txtAreaArchivoLeido.setText(archivoLeido);

    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        btnEditar.setBackground(Color.yellow);
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        btnEditar.setBackground(new Color(204, 255, 255));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtAreaArchivoLeido.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAnalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizarMouseEntered
        btnAnalizar.setBackground(Color.yellow);
    }//GEN-LAST:event_btnAnalizarMouseEntered

    private void btnAnalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizarMouseExited
        btnAnalizar.setBackground(new Color(204, 255, 255));
    }//GEN-LAST:event_btnAnalizarMouseExited

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed

        JFrameTablaTokens tablaTokens = new JFrameTablaTokens();
        Token token = new Token(tablaTokens, reservadas);
        token.analizarDirectiva(txtAreaArchivoLeido.getText());
        tablaTokens.setVisible(true);
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(Color.yellow);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(204, 255, 255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        JFileChooser guardar = new JFileChooser();


        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto (*.pz)", "pz");
        guardar.setFileFilter(filtro);

        int opcion = guardar.showSaveDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File archivo = guardar.getSelectedFile();

        
            if (!archivo.getName().toLowerCase().endsWith(".pz")) {
                archivo = new File(archivo.getAbsolutePath() + ".pz");
            }

            try {
                FileWriter escritor = new FileWriter(archivo);

                escritor.write(txtAreaArchivoLeido.getText());

                escritor.close();

                JOptionPane.showMessageDialog(this,
                        "Archivo guardado correctamente.");

            } catch (IOException e) {

                JOptionPane.showMessageDialog(this,
                        "Error al guardar el archivo: " + e.getMessage());
            }

        }


    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel filas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaArchivoLeido;
    // End of variables declaration//GEN-END:variables
}
